name: Process CSV

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.4'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas

    - name: Run the Python script
      run: python process_csv.py

    - name: Configure Git
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'actions@github.com'

    - name: Commit and push CSV file
      run: |
        git add output.csv
        git commit -m "Add generated CSV file"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
