name: Process CSV

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.4'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas

    - name: Run the Python script
      run: python process_csv.py

    - name: Upload CSV
      uses: actions/upload-artifact@v3
      with:
        name: output-csv
        path: output.csv
